-- ============================================================
-- seed_data.sql — Datos migrados desde Generales_para_todos.xlsx
-- Ejecutar DESPUES de schema.sql
-- ============================================================
USE solutions_db;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE fuera_del_alcance;
TRUNCATE TABLE perfiles;
TRUNCATE TABLE consideraciones;
TRUNCATE TABLE entregables;
TRUNCATE TABLE torres;
SET FOREIGN_KEY_CHECKS = 1;

-- TORRES
INSERT INTO torres (id, nombre, nombre_norm) VALUES
  (1, 'Arquitectura', 'ARQUITECTURA'),
  (2, 'Ciberseguridad', 'CIBERSEGURIDAD'),
  (3, 'Datos', 'DATOS'),
  (4, 'DevOps', 'DEVOPS'),
  (5, 'Fullstack / Desarrollo', 'FULLSTACK / DESARROLLO'),
  (6, 'IA', 'IA'),
  (7, 'Integración', 'INTEGRACION'),
  (8, 'Mobile', 'MOBILE'),
  (9, 'PMO', 'PMO'),
  (10, 'Portales', 'PORTALES'),
  (11, 'QA', 'QA'),
  (12, 'RPA', 'RPA'),
  (13, 'SAP', 'SAP'),
  (14, 'Soporte', 'SOPORTE');

-- PERFILES
INSERT INTO perfiles (torre_id, rol, descripcion) VALUES
  (5, 'Desarrollador Backend Java', 'Experto en desarrollo de servicios backend robustos y escalables usando Java. Implementa APIs REST, lógica de negocio y arquitectura basada en microservicios.'),
  (5, 'Desarrollador  Backend Node', 'Experto en desarrollo backend utilizando Node.js y arquitecturas orientadas a servicios. Construye APIs REST y GraphQL con Express o frameworks modernos.'),
  (5, 'Desarrollador  Backend .NET', 'Experto en desarrollo backend con tecnologías .NET y C#. Implementa servicios REST, lógica empresarial y control de acceso.'),
  (5, 'Desarrollador Backend Python', 'Experto en desarrollo backend utilizando Python para soluciones escalables. Implementa APIs con frameworks como Django y FastAPI. Integra servicios, bases de datos y procesos automatizados.'),
  (5, 'Desarrollador Backend PHP', 'Experto en desarrollo backend con PHP para aplicaciones web. Construye APIs y lógica de negocio con frameworks como Laravel o Symfony.'),
  (5, 'Desarrollador Backend Go', 'Experto en desarrollo backend de alto rendimiento con Go. Diseña servicios eficientes y concurrentes orientados a microservicios. Implementa APIs REST y sistemas distribuidos.'),
  (5, 'Desarrollador Frontend Angular', 'Experto en desarrollo de interfaces web con Angular. Construye aplicaciones escalables basadas en componentes. Implementa consumo de APIs, validaciones y manejo de estados.'),
  (5, 'Desarrollador Frontend React', 'Experto en desarrollo frontend usando React y ecosistema moderno. Crea interfaces dinámicas basadas en componentes reutilizables. Gestiona estados con Redux o herramientas similares.'),
  (5, 'Desarrollador Frontend Vue', 'Experto en desarrollo de interfaces web con Vue.js. Construye aplicaciones modulares y mantenibles. Integra consumo de APIs y manejo de estados. Asegura interfaces intuitivas y eficientes.'),
  (5, 'Desarrollador Frontend UX/UI', 'Experto en diseño y desarrollo de experiencias de usuario. Aplica principios de usabilidad, accesibilidad y diseño visual. Colabora con equipos técnicos para una correcta implementación.'),
  (5, 'Desarrollador Fullstack Java', 'Experto en desarrollo frontend y backend con tecnologías Java. Construye soluciones completas desde la interfaz hasta la base de datos. Integra servicios, APIs y lógica de negocio.'),
  (5, 'Desarrollador Fullstack Node', 'Experto en desarrollo integral con Node.js y tecnologías web modernas. Implementa frontend, backend e integraciones. Diseña soluciones orientadas a servicios y microservicios.'),
  (5, 'Desarrollador Fullstack .NET', 'Experto en desarrollo de aplicaciones completas con .NET. Integra frontend, backend y bases de datos. Implementa arquitecturas empresariales robustas. Asegura calidad, seguridad y escalabilidad.'),
  (5, 'Desarrollador Fullstack Python', 'Experto en desarrollo completo utilizando Python y frameworks web. Implementa interfaces, APIs y lógica de negocio. Integra servicios y bases de datos. Optimiza soluciones de extremo a extremo.'),
  (5, 'Desarrollador Fullstack  PHP', 'Experto en desarrollo fullstack con PHP y tecnologías web. Construye aplicaciones completas y escalables. Integra frontend, backend y servicios externos. Garantiza estabilidad y mantenibilidad.'),
  (5, 'Desarrollador Fullstack Go', 'Experto en desarrollo integral con Go y tecnologías frontend. Implementa servicios backend de alto rendimiento. Integra interfaces y lógica de negocio. Optimiza soluciones completas y eficientes.'),
  (5, 'Desarrollador Fullstack Angular', 'Experto en soluciones completas usando Angular y backend asociado. Desarrolla interfaces modernas y servicios integrados. Gestiona comunicación con APIs y bases de datos.'),
  (5, 'Desarrollador Fullstack React', 'Experto en desarrollo frontend con React y backend integrado. Construye soluciones completas y modernas. Gestiona estados, servicios y persistencia de datos.'),
  (5, 'Desarrollador Fullstack Vue', 'Experto en desarrollo fullstack con Vue.js. Integra frontend, backend y servicios externos. Implementa soluciones modernas y escalables. Garantiza usabilidad y calidad técnica.'),
  (11, 'Analista QA Funcional', 'Experto en validación funcional de aplicaciones y sistemas. Diseña y ejecuta casos de prueba basados en requerimientos. Identifica defectos en flujos de negocio.'),
  (11, 'Analista QA No funcional', 'Experto en pruebas de rendimiento, seguridad y usabilidad. Evalúa estabilidad, carga y comportamiento del sistema. Identifica riesgos técnicos y de desempeño.'),
  (11, 'Coordinador técnico QA', 'Experto en liderazgo y coordinación de equipos de QA. Define estrategias, planes y estándares de calidad. Supervisa ejecución de pruebas funcionales y técnicas.'),
  (11, 'Analista QA Automatizador', 'Experto en automatización de pruebas funcionales y regresión. Diseña scripts con herramientas especializadas. Optimiza tiempos de prueba y detección temprana de fallos.'),
  (1, 'Arquitecto Software', 'Experto en diseño de arquitecturas de software empresariales. Define patrones, estándares y lineamientos técnicos. Garantiza escalabilidad, seguridad y mantenibilidad.'),
  (1, 'Arquitecto Empresarial', 'Experto en alineación de tecnología y estrategia empresarial. Define modelos de negocio y arquitecturas organizacionales. Optimiza procesos y sistemas. Asegura coherencia entre negocio y TI.'),
  (1, 'Arquitecto Cloud', 'Experto en diseño de arquitecturas en la nube. Define soluciones escalables, seguras y eficientes. Optimiza costos y disponibilidad. Implementa mejores prácticas cloud.'),
  (1, 'Arquitecto de Soluciones', 'Experto en diseño de soluciones tecnológicas end-to-end. Integra múltiples sistemas y plataformas. Define arquitectura, componentes y flujos. Garantiza viabilidad técnica y funcional.'),
  (3, 'Ingeniero de Datos', 'Experto en diseño, construcción y mantenimiento de pipelines de datos. Gestiona ingesta, transformación y almacenamiento de grandes volúmenes.'),
  (3, 'Análista de datos', 'Experto en análisis, interpretación y visualización de datos. Transforma datos en información útil para la toma de decisiones. Utiliza herramientas de BI y análisis estadístico.'),
  (3, 'Arquitecto de Datos', 'Experto en diseño de arquitecturas de datos empresariales. Define modelos, flujos y estándares de información. Garantiza integridad, seguridad y escalabilidad.'),
  (3, 'Data Technical Lead', 'Experto en liderazgo técnico de equipos de datos. Define lineamientos, arquitecturas y buenas prácticas. Supervisa la implementación de soluciones analíticas.'),
  (3, 'Data Scientist', 'Experto en análisis avanzado, estadística y modelos predictivos. Desarrolla algoritmos de machine learning y análisis exploratorio. Extrae patrones y predicciones a partir de datos.'),
  (3, 'Data Analyst', 'Experto en análisis descriptivo y visualización de datos. Construye reportes y dashboards ejecutivos. Identifica tendencias y oportunidades de mejora. Facilita la toma de decisiones del negocio.'),
  (3, 'Ingeniero Pyton', 'Experto en desarrollo de soluciones con Python. Automatiza procesos y construye servicios backend. Integra APIs, bases de datos y scripts. Aplica buenas prácticas de desarrollo y rendimiento.'),
  (12, 'Desarrolladores Power Platform Junior', 'Experto en desarrollo básico acon Power Apps y Power Automate. Construye aplicaciones y flujos sencillos. Apoya procesos de automatización empresarial. Trabaja bajo lineamientos técnicos definidos.'),
  (12, 'Desarrolladores Power Platform Mid', 'Experto en desarrollo intermedio con Power Platform. Diseña aplicaciones y automatizaciones más complejas. Integra fuentes de datos y servicios externos. Optimiza procesos de negocio.'),
  (12, 'Desarrolladores Power Platform Senior', 'Experto en diseño de soluciones avanzadas con Power Platform. Define arquitectura, estándares y buenas prácticas. Lidera desarrollos complejos y estratégicos. Asegura escalabilidad y mantenibilidad.'),
  (12, 'Desarrolladores Dynamics CRM Junior', 'Experto en configuración básica de Dynamics CRM. Apoya personalización de formularios y flujos. Gestiona datos y procesos simples. Trabaja bajo supervisión técnica.'),
  (12, 'Desarrolladores Dynamics CRM Mid', 'Experto en desarrollo y personalización de Dynamics CRM. Implementa flujos, integraciones y lógica de negocio. Optimiza procesos comerciales y operativos. Garantiza estabilidad de la plataforma.'),
  (12, 'Desarrolladores Dynamics CRM Senior', 'Experto en arquitectura y desarrollo avanzado en Dynamics CRM. Diseña soluciones empresariales complejas. Lidera integraciones y personalizaciones críticas.'),
  (12, 'Desarrolladores RPA Junior', 'Experto en automatización básica de procesos con RPA. Construye bots simples y flujos repetitivos. Apoya iniciativas de automatización. Trabaja siguiendo estándares definidos.'),
  (12, 'Desarrolladores RPA Mid', 'Experto en automatización de procesos de complejidad media. Diseña y mantiene bots robustos. Integra sistemas y valida procesos. Optimiza eficiencia operativa.'),
  (12, 'Desarrolladores RPA Senior', 'Experto en diseño de estrategias de automatización RPA. Define arquitectura y estándares de bots. Lidera automatizaciones críticas. Asegura escalabilidad y gobierno RPA.'),
  (4, 'Ingeniero DevOps', 'Experto en integración y entrega continua (CI/CD). Automatiza despliegues y gestión de infraestructura. Optimiza entornos de desarrollo y producción. Mejora estabilidad y velocidad de entrega.'),
  (4, 'DevOps Junior', 'Experto en soporte a procesos DevOps básicos. Apoya pipelines, despliegues y monitoreo. Gestiona tareas operativas. Trabaja bajo lineamientos establecidos.'),
  (4, 'DevOps Intermedio', 'Experto en implementación y mejora de pipelines CI/CD. Automatiza infraestructura y despliegues. Gestiona entornos cloud. Optimiza procesos DevOps.'),
  (4, 'DevOps Senior', 'Experto en estrategia DevOps empresarial. Define arquitecturas, estándares y automatización avanzada. Lidera iniciativas de mejora continua. Garantiza estabilidad y escalabilidad.'),
  (4, 'Ingenieros de Plataforma', 'Experto en diseño y operación de plataformas tecnológicas. Gestiona infraestructura, servicios y herramientas base. Optimiza disponibilidad y rendimiento. Soporta equipos de desarrollo y operaciones.'),
  (4, 'IAOPS', 'Experto en operación y despliegue de soluciones de IA. Automatiza ciclos de vida de modelos. Gestiona monitoreo y escalabilidad. Asegura confiabilidad de modelos en producción.'),
  (4, 'Propuestas', 'Experto en elaboración y estructuración de propuestas técnicas. Define alcances, perfiles y estimaciones. Alinea soluciones con requerimientos del cliente. Apoya procesos comerciales y preventa.'),
  (4, 'Gestión Fabrica', 'Experto en gestión de equipos y servicios de desarrollo. Coordina recursos, tiempos y entregables. Optimiza productividad y calidad. Asegura cumplimiento de SLAs.'),
  (4, 'Arquitecto IA', 'Experto en diseño de arquitecturas basadas en inteligencia artificial. Define modelos, plataformas y flujos de datos. Integra IA en soluciones empresariales. Asegura escalabilidad y gobernanza.'),
  (4, 'Ingeniero de ML', 'Experto en desarrollo y entrenamiento de modelos de machine learning. Optimiza algoritmos y pipelines de datos. Integra modelos en producción. Mejora precisión y desempeño.'),
  (4, 'Arquitecto DevSecOps', 'Experto en integración de seguridad en DevOps. Define controles y automatización de seguridad. Gestiona riesgos y cumplimiento. Asegura entornos seguros desde el desarrollo.'),
  (2, 'Analista Ciberseguridad Sr', 'Experto en identificación y gestión de riesgos de seguridad. Evalúa vulnerabilidades y define controles de protección. Apoya implementación de políticas de seguridad.'),
  (2, 'Analista de Ciberseguridad', 'Experto en análisis y mitigación de amenazas de ciberseguridad. Monitorea sistemas y detecta incidentes de seguridad. Implementa controles y buenas prácticas de seguridad.'),
  (6, 'Ingeniero IA', 'Experto en desarrollo de soluciones basadas en IA. Implementa modelos y servicios inteligentes. Integra IA con sistemas existentes. Optimiza procesos mediante automatización.'),
  (13, 'Consultor SAP MM', 'Experto en gestión de materiales y cadena de suministro en SAP. Configura procesos de compras, inventarios y proveedores. Optimiza abastecimiento y control de stock.'),
  (13, 'Consultor SAP SD', 'Experto en gestión de ventas y distribución en SAP. Configura procesos de pedidos, facturación y entregas. Optimiza el ciclo comercial y la relación con clientes.'),
  (13, 'Consultor SAP CO', 'Experto en control de costos y contabilidad interna en SAP. Configura centros de costo, órdenes internas y análisis financiero. Apoya la planificación y control presupuestal.'),
  (13, 'Consultor SAP FI', 'Experto en contabilidad financiera y gestión contable en SAP. Configura procesos de contabilidad general y fiscal. Asegura cumplimiento normativo y financiero.'),
  (13, 'Consultor SAP WM', 'Experto en gestión de almacenes mediante SAP WM. Configura procesos de recepción, almacenamiento y despacho. Optimiza la logística interna y control de inventarios.'),
  (13, 'Consultor SAP PM', 'Experto en mantenimiento de planta y activos en SAP. Configura planes de mantenimiento y órdenes de trabajo. Optimiza la gestión de equipos y activos. Reduce tiempos de parada y costos operativos.'),
  (13, 'Consultor SAP PP', 'Experto en planificación y control de la producción en SAP. Configura órdenes de producción y listas de materiales. Optimiza la programación y capacidad productiva.'),
  (13, 'Consultor SAP ABAP', 'Experto en desarrollo y personalización SAP ABAP. Implementa reportes, interfaces y mejoras. Optimiza rendimiento del sistema. Soporta soluciones SAP avanzadas.'),
  (13, 'Consultor SAP Integration Suite', 'Experto en integraciones SAP Cloud. Diseña flujos entre sistemas SAP y externos. Asegura interoperabilidad. Optimiza procesos de integración.'),
  (13, 'Consultor SAP BTP Analytics Cloud', 'Experto en analítica y visualización SAP BTP. Construye dashboards y reportes estratégicos. Apoya toma de decisiones. Optimiza análisis empresarial.'),
  (13, 'Consultor BTP DEV', 'Experto en desarrollo sobre SAP BTP. Implementa aplicaciones cloud nativas. Integra servicios y datos. Optimiza soluciones SAP modernas.'),
  (13, 'Consultor Tecnico B1', 'Experto en implementación y soporte técnico de SAP Business One. Configura y administra la plataforma a nivel técnico. Desarrolla personalizaciones, integraciones y extensiones.'),
  (13, 'Consultor SAP B1', 'Experto en implementación funcional de SAP Business One. Configura procesos empresariales y flujos operativos. Acompaña al usuario en la adopción de la solución.'),
  (13, 'Consultor SAP CX', 'Experto en soluciones SAP enfocadas en experiencia del cliente. Optimiza procesos comerciales y de atención al cliente. Configura e integra módulos de SAP CX.'),
  (13, 'Consultor SAP Succesfactors', 'Experto en soluciones SAP para gestión del talento humano. Optimiza procesos de recursos humanos y nómina. Configura e integra módulos de SuccessFactors. Mejora la gestión del capital humano.'),
  (13, 'Consultor SAP Q1', 'Experto en soporte SAP de primer nivel. Atiende incidencias básicas y solicitudes de usuario. Da soporte operativo y funcional inicial. Garantiza continuidad del servicio.'),
  (13, 'Consultor SAP Q2', 'Experto en soporte SAP de segundo nivel. Resuelve incidencias de mayor complejidad. Analiza causas raíz y propone mejoras. Asegura estabilidad y operación continua del sistema.'),
  (9, 'Scrum', 'Experto en aplicación de marcos ágiles Scrum. Facilita ceremonias y seguimiento. Optimiza trabajo del equipo. Asegura entrega continua de valor.'),
  (9, 'Gerente de Proyecto', 'Experto en gestión integral de proyectos. Coordina alcance, tiempo y costos. Gestiona riesgos y stakeholders. Asegura cumplimiento de objetivos.'),
  (9, 'Analistas funcionales', 'Experto en levantamiento y análisis de requerimientos. Traduce necesidades del negocio a soluciones. Coordina con equipos técnicos. Asegura alineación funcional.'),
  (8, 'Desarrollador Mobile IOS', 'Experto en desarrollo de aplicaciones móviles iOS. Implementa interfaces nativas y funcionalidad. Integra servicios y APIs. Optimiza rendimiento y experiencia.'),
  (8, 'Desarrollador Mobile Flutter, React Native', 'Experto en desarrollo de aplicaciones móviles multiplataforma. Construye soluciones para iOS y Android con Flutter y React Native. Integra servicios backend, APIs y bases de datos.'),
  (8, 'Desarrollador Mobile Flutter, Ionic', 'Experto en desarrollo de aplicaciones móviles multiplataforma. Implementa soluciones móviles usando Flutter e Ionic. Integra funcionalidades, servicios y APIs.'),
  (8, 'Lider tecnico', 'Experto en liderazgo técnico de equipos. Define lineamientos y arquitectura. Apoya toma de decisiones técnicas. Garantiza calidad del desarrollo'),
  (10, 'Consultor De Desarrollo', 'Experto en asesoría y acompañamiento técnico en proyectos de desarrollo. Analiza requerimientos y propone soluciones tecnológicas adecuadas.'),
  (10, 'Analista Funcional', 'Experto en levantamiento y análisis de requerimientos del negocio. Traduce necesidades funcionales en especificaciones claras. Actúa como enlace entre usuarios y equipo técnico.'),
  (10, 'Desarrollador Liferay', 'Especialista en la plataforma Liferay DXP. Implementa y migra portales empresariales a arquitecturas modernas. Garantiza continuidad operativa, seguridad y escalabilidad.'),
  (10, 'Analista Desarrollador', 'Experto en análisis y desarrollo de soluciones tecnológicas. Combina visión funcional con implementación técnica. Desarrolla y ajusta aplicaciones según requerimientos.'),
  (7, 'Arquitecto de Integración', 'Experto en diseño de arquitecturas de integración. Define flujos entre sistemas. Asegura interoperabilidad. Optimiza comunicación empresarial.'),
  (7, 'Líder Técnico de Integración', 'Experto en liderazgo de proyectos de integración. Coordina equipos y soluciones. Define estándares técnicos. Asegura calidad de integraciones.'),
  (7, 'Desarrollador de Integración', 'Experto en desarrollo de servicios e integraciones. Implementa APIs y conectores. Gestiona flujos de datos. Optimiza interoperabilidad.'),
  (7, 'Especialista Cloud de Integración', 'Experto en integraciones en entornos cloud. Diseña soluciones escalables. Integra servicios cloud y on-premise. Optimiza rendimiento y seguridad.'),
  (7, 'DevOps de Integración', 'Experto en automatización y despliegue de integraciones. Gestiona pipelines CI/CD de integración. Optimiza entornos y monitoreo. Asegura entregas continuas y estables.');

-- FUERA DEL ALCANCE
INSERT INTO fuera_del_alcance (torre_id, item, orden) VALUES
  (5, 'No incluye desarrollo de funcionalidades no especificadas en la propuesta.', 0),
  (5, 'No incluye integración con aplicaciones o sistemas no mencionados.', 1),
  (5, 'No incluye licenciamiento de herramientas o componentes de terceros.', 2),
  (5, 'No incluye participación de diseñador UX/UI.', 3),
  (5, 'No incluye actualización o migración de versiones tecnológicas existentes.', 4),
  (5, 'No incluye optimización avanzada de rendimiento fuera del alcance definido.', 5),
  (5, 'No incluye soporte posterior al periodo de garantía.', 6),
  (5, 'No incluye responsabilidad por deuda técnica preexistente.', 7),
  (5, 'No incluye hardening de seguridad.', 8),
  (5, 'No incluye definición de arquitectura empresarial.', 9),
  (5, 'No incluye despliegues en múltiples ambientes si no están definidos.', 10),
  (5, 'No incluye monitoreo productivo.', 11),
  (5, 'No incluye refactorización completa de código legado.', 12),
  (11, 'No incluye ejecución de pruebas no contempladas explícitamente en el alcance aprobado.', 0),
  (11, 'No incluye pruebas de seguridad si no están definidas en la estimación.', 1),
  (11, 'No incluye pruebas de performance, carga o estrés si no están incluidas.', 2),
  (11, 'No incluye pruebas automatizadas adicionales no contempladas.', 3),
  (11, 'No incluye pruebas responsive si no están definidas.', 4),
  (11, 'No incluye pruebas en ambientes productivos.', 5),
  (11, 'No incluye certificaciones regulatorias.', 6),
  (11, 'No incluye validaciones con usuarios finales (UAT) si no están contempladas.', 7),
  (11, 'No incluye ambientes dedicados de prueba.', 8),
  (11, 'No incluye generación de evidencia para auditorías externas.', 9),
  (11, 'No incluye pruebas de compatibilidad con navegadores o dispositivos no definidos.', 10),
  (1, 'No incluye implementación técnica directa de las soluciones recomendadas.', 0),
  (1, 'No incluye operación continua posterior a la entrega del informe.', 1),
  (1, 'No incluye gestión de infraestructura corporativa.', 2),
  (1, 'No incluye evaluación de cultura organizacional o transformación ágil fuera del alcance definido.', 3),
  (1, 'No incluye realización de pilotos derivados de la consultoría.', 4),
  (1, 'No incluye gestión del cambio organizacional.', 5),
  (1, 'No incluye roadmap tecnológico corporativo completo.', 6),
  (1, 'No incluye arquitectura cloud si no está expresamente definida.', 7),
  (1, 'No incluye definición de modelo operativo TI.', 8),
  (1, 'No incluye implementación DevOps.', 9),
  (1, 'No incluye configuración real de nube.', 10),
  (1, 'No incluye definición de políticas de seguridad corporativa.', 11),
  (1, 'No incluye definición de estándares corporativos globales.', 12),
  (3, 'No incluye migración masiva de datos históricos.', 0),
  (3, 'No incluye saneamiento o corrección de bases de datos existentes.', 1),
  (3, 'No incluye administración continua de bases de datos o plataformas analíticas.', 2),
  (3, 'No incluye licenciamiento de herramientas BI.', 3),
  (3, 'No incluye gobierno corporativo de datos completo.', 4),
  (3, 'No incluye operación continua de pipelines de datos.', 5),
  (3, 'No incluye modelado de gobierno MDM.', 6),
  (3, 'No incluye calidad de datos corporativa integral.', 7),
  (3, 'No incluye tuning avanzado de bases productivas.', 8),
  (3, 'No incluye optimización de costos cloud.', 9),
  (3, 'No incluye anonimización o enmascaramiento de datos sensibles.', 10),
  (12, 'No incluye desarrollo de bots adicionales no contemplados en la propuesta.', 0),
  (12, 'No incluye integración con aplicaciones no mencionadas.', 1),
  (12, 'No incluye licenciamiento de herramientas RPA.', 2),
  (12, 'No incluye migración de información histórica.', 3),
  (12, 'No incluye infraestructura RPA productiva.', 4),
  (12, 'No incluye soporte continuo posterior al periodo definido.', 5),
  (12, 'No incluye modificaciones en sistemas externos automatizados.', 6),
  (12, 'No incluye pruebas de carga o estrés no contempladas.', 7),
  (12, 'No incluye bots unattended productivos.', 8),
  (12, 'No incluye orquestadores empresariales.', 9),
  (12, 'No incluye cambios en aplicativos legacy.', 10),
  (12, 'No incluye análisis forense de procesos.', 11),
  (12, 'No incluye continuidad operativa ante cambios en interfaces de sistemas de terceros.', 12),
  (4, 'No incluye licenciamiento de herramientas SAST, DAST, SCA o similares.', 0),
  (4, 'No incluye licenciamiento de herramientas de monitoreo.', 1),
  (4, 'No incluye licenciamiento de herramientas CI/CD.', 2),
  (4, 'No incluye costos de consumo de infraestructura cloud.', 3),
  (4, 'No incluye operación continua ni administración permanente de infraestructura.', 4),
  (4, 'No incluye migración de aplicaciones distintas al alcance definido.', 5),
  (4, 'No incluye implementación de pruebas avanzadas en producción (IAST, pentesting externo).', 6),
  (4, 'No incluye gestión corporativa centralizada de identidades (IAM).', 7),
  (4, 'No incluye planes de recuperación ante desastres (DRP).', 8),
  (4, 'No incluye definición de estrategia multicloud.', 9),
  (4, 'No incluye FinOps.', 10),
  (4, 'No incluye monitoreo 24/7.', 11),
  (4, 'No incluye auditoría de cumplimiento normativo.', 12),
  (4, 'No incluye configuración de alta disponibilidad (HA) no especificada.', 13),
  (2, 'No incluye desarrollo de flujos de autenticación.', 0),
  (2, 'No incluye implementación de KMS o HSM.', 1),
  (2, 'No incluye operación del SOC o SIEM.', 2),
  (2, 'No incluye implementación ni operación de MDM.', 3),
  (2, 'No incluye pruebas DoS reales o destructivas.', 4),
  (2, 'No incluye decisión final de aceptación de riesgos.', 5),
  (2, 'No incluye operación post-producción.', 6),
  (2, 'No incluye remediación de vulnerabilidades identificadas.', 7),
  (2, 'No incluye certificaciones regulatorias formales.', 8),
  (2, 'No incluye ethical hacking continuo.', 9),
  (2, 'No incluye implementación de modelo Zero Trust.', 10),
  (2, 'No incluye SOC 24/7.', 11),
  (2, 'No incluye aseguramiento frente a entes reguladores.', 12),
  (2, 'No incluye monitoreo continuo de amenazas.', 13),
  (6, 'No incluye desarrollo de módulos operativos adicionales no descritos.', 0),
  (6, 'No incluye integraciones distintas a las expresamente definidas.', 1),
  (6, 'No incluye entrenamiento continuo del modelo.', 2),
  (6, 'No incluye custodia de datos sensibles.', 3),
  (6, 'No incluye optimización de costos por consumo de APIs o servicios cognitivos.', 4),
  (6, 'No incluye explicabilidad avanzada (XAI).', 5),
  (6, 'No incluye infraestructura dedicada GPU.', 6),
  (6, 'No incluye reentrenamiento por deriva de modelo (model drift).', 7),
  (13, 'No incluye licenciamiento SAP.', 0),
  (13, 'No incluye actividades de despliegue en ambientes si no están definidas.', 1),
  (13, 'No incluye desarrollos en tecnologías distintas a SAP.', 2),
  (13, 'No incluye construcción de APIs o BAPIs no especificadas.', 3),
  (13, 'No incluye desarrollos nuevos fuera del RFP aprobado.', 4),
  (13, 'No incluye actualización o migración de versión SAP.', 5),
  (13, 'No incluye soporte funcional continuo.', 6),
  (13, 'No incluye migración ni saneamiento de datos históricos.', 7),
  (13, 'No incluye optimización avanzada de rendimiento.', 8),
  (13, 'No incluye responsabilidad por deuda técnica preexistente.', 9),
  (13, 'No incluye servicios BASIS.', 10),
  (13, 'No incluye parametrizaciones funcionales no descritas.', 11),
  (13, 'No incluye upgrade técnico ECC o S/4HANA.', 12),
  (13, 'No incluye integraciones IDoc adicionales.', 13),
  (13, 'No incluye transportes entre ambientes si no están definidos.', 14),
  (9, 'La propuesta se limita exclusivamente a los programas definidos.', 0),
  (9, 'No incluye implementación de herramientas.', 1),
  (9, 'No incluye ejecución de proyectos derivados de la capacitación.', 2),
  (9, 'No incluye acompañamiento operativo posterior.', 3),
  (9, 'No incluye consultoría estratégica adicional.', 4),
  (9, 'No incluye rediseño organizacional fuera del alcance definido.', 5),
  (9, 'No incluye PMO permanente.', 6),
  (9, 'No incluye gestión contractual.', 7),
  (9, 'No incluye auditoría financiera del proyecto.', 8),
  (8, 'No incluye licenciamiento de plugins de pago.', 0),
  (8, 'No incluye diseñador UX/UI.', 1),
  (8, 'No incluye publicación en tiendas de aplicaciones.', 2),
  (8, 'No incluye soporte a dispositivos no certificados o modificados.', 3),
  (8, 'No se garantiza compatibilidad con versiones de sistema operativo no soportadas oficialmente.', 4),
  (8, 'No incluye integración con asistentes de voz.', 5),
  (8, 'No incluye soporte evolutivo posterior al periodo de garantía.', 6),
  (8, 'No incluye responsabilidad por fallas de hardware del dispositivo.', 7),
  (8, 'No incluye pruebas no contempladas en el alcance.', 8),
  (8, 'No incluye desarrollo de backend adicional no definido.', 9),
  (8, 'No incluye publicación en múltiples stores si no está especificado.', 10),
  (8, 'No incluye compatibilidad con dispositivos fuera de soporte oficial.', 11),
  (10, 'No incluye desarrollo de módulos adicionales no especificados.', 0),
  (10, 'No incluye integraciones con CMS no contempladas.', 1),
  (10, 'No incluye diseño gráfico adicional.', 2),
  (10, 'No incluye desarrollo multilenguaje.', 3),
  (10, 'No incluye administración continua del portal.', 4),
  (10, 'No incluye migración de información histórica.', 5),
  (10, 'No incluye pruebas de carga o performance no definidas.', 6),
  (10, 'No incluye SEO.', 7),
  (10, 'No incluye estrategia de contenidos.', 8),
  (10, 'No incluye CDN empresarial.', 9),
  (10, 'No incluye administración editorial continua.', 10),
  (7, 'No incluye desarrollo de lógica de negocio en sistemas externos.', 0),
  (7, 'No incluye cambios en sistemas externos no definidos en el alcance.', 1),
  (7, 'No incluye analítica predictiva fuera del alcance aprobado.', 2),
  (7, 'No incluye integraciones adicionales no mencionadas.', 3),
  (7, 'No incluye dashboards externos ni BI avanzado.', 4),
  (7, 'No incluye implementación de remediaciones técnicas en sistemas de terceros.', 5),
  (7, 'No incluye garantía de SLA de sistemas externos.', 6),
  (7, 'No incluye costos de licenciamiento o consumo de plataformas de integración o cloud.', 7),
  (7, 'No incluye operación continua posterior al periodo definido.', 8),
  (7, 'No incluye ESB corporativo.', 9),
  (7, 'No incluye gobernanza de APIs.', 10),
  (7, 'No incluye monitoreo transaccional 24/7.', 11),
  (7, 'No incluye transformación masiva histórica de datos.', 12),
  (7, 'No incluye transformación estructural de datos en sistemas externos.', 13);

-- CONSIDERACIONES
INSERT INTO consideraciones (torre_id, texto, es_general, orden) VALUES
  (5, 'XXXXXXXXXX deberá brindar acceso a los ambientes de desarrollos y pruebas para la ejecución del proyecto.', 0, 0),
  (5, 'XXXXXXXXXX brindará el acceso a los repositorios, herramientas, fuentes, base de datos y referentes para la atención del proyecto​.', 0, 1),
  (5, 'XXXXXXXXXX garantizará la disponibilidad de equipos clave para sesiones de levantamiento y aprobación.​', 0, 2),
  (5, 'XXXXXXXXXX deberá brindar VPN en caso de que sea necesario​.', 0, 3),
  (5, 'Filial, utilizará los estándares de buenas prácticas para los desarrollos.​', 0, 4),
  (5, 'XXXXXXXXXX debe suministrar todos los componentes de infraestructura y licencias para el proyecto.​', 0, 5),
  (5, 'XXXXXXXXXX debe suministrar los insumos necesarios para la ejecución de las pruebas unitarias en ambiente de desarrollo y calidad.', 0, 6),
  (5, 'XXXXXXXXXX realizará los despliegues con el acompañamiento de Filial.', 0, 7),
  (5, 'XXXXXXXXXX garantizará que los requisitos no cambiarán significativamente durante este desarrollo.', 0, 8),
  (5, 'XXXXXXXXXX debera levantar y refinar las historias de usuario para realizar sesiones de entendimiento con Filial.', 0, 9),
  (5, 'XXXXXXXXXX proporcionará la infraestructura y se emplearán los servicios actuales de comunicaciones y servidores. ​', 0, 10),
  (14, 'XXXXXXXXXX proveerá y facilitará acceso de manera oportuna a usuarios, credenciales y documentación de los servicios, ambientes y herramientas.​', 0, 0),
  (14, 'XXXXXXXXXX garantizará la disponibilidad de equipos clave para sesiones de levantamiento de información.​', 0, 1),
  (14, 'XXXXXXXXXX debe suministrar los insumos necesarios para la ejecución de las pruebas en ambiente de desarrollo y calidad.​', 0, 2),
  (14, 'XXXXXXXXXX brindará licenciamiento, recursos de infraestructura, ambientes de desarrollo, prueba y producción necesario para los desarrollos realizados por Filial.', 0, 3),
  (14, 'Filial proveerá el capacity técnico para el servicio.', 0, 4),
  (14, 'Filial deberá cumplir con los ANS establecidos por XXXXXXXXX.', 0, 5),
  (14, 'Filial propone los siguientes ANS para el cumplimiento de los entregables.', 0, 6),
  (14, 'XXXXXXXXXX deberá notificar a la filial con x días de antelación para la activación del servicio.', 0, 7),
  (8, 'XXXXXXXXXX proveerá y facilitará acceso de manera oportuna a usuarios, credenciales y documentación de los servicios, ambientes y herramientas.​', 0, 0),
  (8, 'XXXXXXXXXX garantizará las historias de usuario levantadas y refinadas para entregar a Filial.​', 0, 1),
  (8, 'XXXXXXXXXX debe suministrar los insumos necesarios para la ejecución de las pruebas en ambiente de desarrollo y calidad.​', 0, 2),
  (8, 'XXXXXXXXXX brindará licenciamiento, recursos de infraestructura, ambientes de desarrollo, prueba y producción necesario para los desarrollos realizados por Filial.​', 0, 3),
  (8, 'Filial debe suministrar todos los componentes de infraestructura y licencias para el proyecto.​', 0, 4),
  (8, 'XXXXXXXXXX debe suministrar los insumos necesarios para la ejecución de las pruebas unitarias en ambiente de desarrollo y calidad.', 0, 5),
  (8, 'XXXXXXXXXX realizará los despliegues con el acompañamiento Filial.', 0, 6),
  (8, 'XXXXXXXXXX brindará el acceso a los repositorios, herramientas, fuentes, base de datos y referentes para la atención del proyecto.', 0, 7),
  (8, 'XXXXXXXXXX garantizará que los requisitos no cambiarán significativamente durante este desarrollo.', 0, 8),
  (8, 'Filial construirá los desarrollos en las siguientes tecnologias', 0, 9),
  (10, 'XXXXXXXXXX garantizará que los ambientes (Dev, QA y Producción) se encuentren configurados y disponibles para poder iniciar con el desarrollo del proyecto.', 0, 0),
  (10, 'XXXXXXXXXX proporcionará de manera oportuna el acceso a los ambientes y plataformas para gestión de las entregas.', 0, 1),
  (10, 'XXXXXXXXXX entregará la data para las validaciones de aseguramiento de calidad.', 0, 2),
  (10, 'XXXXXXXXXX proporcionará la infraestructura y se emplearán los servicios actuales de comunicaciones y servidores. ​', 0, 3),
  (11, 'XXXXXXXXXX garantizará la disponibilidad de equipos clave para sesiones de levantamiento y aprobación.​', 0, 0),
  (11, 'XXXXXXXXXX proveerá y facilitará acceso de manera oportuna a credenciales y documentación de los servicios, ambientes y herramientas necesarias para la prestación del servicio.', 0, 1),
  (11, 'Filial prestará los servicios de manera remota.', 0, 2),
  (11, 'XXXXXXXXXX proporcionará la infraestructura y se emplearán los servicios actuales de comunicaciones y servidores. ​', 0, 3),
  (11, 'Filial realizará el acompañamiento a los despliegues.', 0, 4),
  (11, 'XXXXXXXXXX garantizará que los requisitos y criterios de aceptación no cambiarán significativamente durante este desarrollo.', 0, 5),
  (12, 'XXXXXXXXXX asumirá que el acceso al sistema core no requiere cambios estructurales.', 0, 0),
  (12, 'Filial prestará los servicios de manera remota.', 0, 1),
  (12, 'XXXXXXXXXX asume disponibilidad de ambiente de pruebas.', 0, 2),
  (12, 'Filial contempla ejecución RPA conectado a Power Automate Cloud.', 0, 3),
  (12, 'XXXXXXXXXX deberá brindar acceso a los ambientes de desarrollos y pruebas para la ejecución del proyecto.', 0, 4),
  (12, 'XXXXXXXXXX brindará el acceso a los repositorios, herramientas, fuentes, base de datos y referentes para la atención del proyecto​', 0, 5),
  (NULL, 'XXXXXXXXXX deberá brindar acceso a los ambientes de desarrollos, pruebas y producción pruebas para la ejecución del proyecto', 1, 0),
  (NULL, 'XXXXXXXXXX deberá brindar VPN en caso de que sea necesario.', 1, 1),
  (NULL, 'Filial brindará el acceso a los repositorios, herramientas, código fuente, base de datos y referentes para la atención del proyecto.', 1, 2),
  (NULL, 'XXXXXXXXXX deberá suministrar los insumos necesarios para la ejecución de las pruebas en ambiente de desarrollo y calidad.', 1, 3),
  (NULL, 'XXXXXXXXXX brindará licencias en caso que sea necesario.', 1, 4),
  (NULL, 'La modalidad de trabajo es Remota, sin embargo, si se requiere presencialidad puede ser negociado en la fase de contratación.', 1, 5),
  (NULL, 'XXXXXXXXXX entregará la data para las validaciones de aseguramiento de calidad.', 1, 6);

-- ENTREGABLES
INSERT INTO entregables (torre_id, item, orden) VALUES
  (5, 'Arquitectura técnica', 0),
  (5, 'Servicios / APIs', 1),
  (5, 'Portal o aplicación', 2),
  (5, 'Integraciones', 3),
  (5, 'Código fuente documentado', 4),
  (11, 'Plan de pruebas', 0),
  (11, 'Casos de prueba', 1),
  (11, 'Ejecución de pruebas', 2),
  (11, 'Reportes de defectos', 3),
  (11, 'Informe de calidad', 4),
  (1, 'Arquitectura objetivo', 0),
  (1, 'Diagramas de arquitectura', 1),
  (1, 'Modelo de integración', 2),
  (1, 'Gobierno tecnológico', 3),
  (1, 'Hoja de ruta de arquitectura', 4),
  (3, 'Modelo de datos', 0),
  (3, 'Diccionario de datos', 1),
  (3, 'Flujos de información', 2),
  (3, 'Reglas de calidad de datos', 3),
  (3, 'Gobierno de datos', 4),
  (12, 'Procesos automatizados', 0),
  (12, 'Bots desarrollados', 1),
  (12, 'Orquestación de procesos', 2),
  (12, 'Documentación de automatizaciones', 3),
  (12, 'Manuales operativos', 4),
  (4, 'Pipelines CI/CD', 0),
  (4, 'Infraestructura como código', 1),
  (4, 'Automatización de despliegues', 2),
  (4, 'Monitoreo y observabilidad', 3),
  (4, 'Gestión de entornos', 4),
  (2, 'Evaluación de riesgos', 0),
  (2, 'Arquitectura de seguridad', 1),
  (2, 'Controles de seguridad', 2),
  (2, 'Pruebas de seguridad', 3),
  (2, 'Plan de respuesta a incidentes', 4),
  (6, 'Modelos de IA entrenados', 0),
  (6, 'Pipelines de datos', 1),
  (6, 'APIs de inferencia', 2),
  (6, 'Documentación técnica', 3),
  (6, 'Monitoreo de modelos', 4),
  (13, 'Blueprint funcional', 0),
  (13, 'Configuración SAP', 1),
  (13, 'Desarrollos ABAP', 2),
  (13, 'Integraciones SAP', 3),
  (13, 'Documentación técnica y funcional', 4),
  (9, 'Plan del proyecto', 0),
  (9, 'Cronograma', 1),
  (9, 'Gestión de riesgos', 2),
  (9, 'Reportes de avance', 3),
  (9, 'Actas y documentación de gobierno', 4),
  (8, 'Aplicación móvil', 0),
  (8, 'Diseño UX/UI', 1),
  (8, 'Backend móvil', 2),
  (8, 'Documentación técnica', 3),
  (10, 'Portal web', 0),
  (10, 'Diseño UX/UI', 1),
  (10, 'Módulos funcionales', 2),
  (10, 'Integraciones', 3),
  (10, 'Documentación técnica', 4),
  (7, 'Arquitectura de integración', 0),
  (7, 'Servicios de integración', 1),
  (7, 'Flujos de orquestación', 2),
  (7, 'Conectores', 3),
  (7, 'Documentación de integración', 4);

-- FIN DEL SCRIPT